"""
AURA Journalist Response Generator
Detailed fact-check reports for journalists
"""

from typing import Dict, Any, List, Optional
from datetime import datetime

from app.core.logging import logger


class JournalistResponse:
    """
    Generates detailed fact-check reports for journalists.
    Includes methodology, evidence analysis, and source citations.
    """
    
    def __init__(self):
        pass
    
    def generate(
        self,
        claim: str,
        verdict: str,
        confidence: float,
        reasoning: str,
        debate_summary: Dict = None,
        evidence: List[Dict] = None,
        quick_classification: Dict = None,
        verification_id: str = None
    ) -> Dict[str, Any]:
        """
        Generate journalist-friendly detailed report.
        """
        report = self._build_report(
            claim=claim,
            verdict=verdict,
            confidence=confidence,
            reasoning=reasoning,
            debate_summary=debate_summary,
            evidence=evidence,
            quick_classification=quick_classification,
            verification_id=verification_id
        )
        
        return {
            "type": "journalist",
            "verification_id": verification_id,
            "claim": claim,
            "verdict": verdict,
            "confidence": confidence,
            "report_markdown": report,
            "report_sections": self._get_sections(report),
            "citation_count": len(evidence) if evidence else 0,
            "timestamp": datetime.utcnow().isoformat()
        }
    
    def _build_report(
        self,
        claim: str,
        verdict: str,
        confidence: float,
        reasoning: str,
        debate_summary: Dict,
        evidence: List[Dict],
        quick_classification: Dict,
        verification_id: str
    ) -> str:
        """Build markdown report."""
        confidence_pct = int(confidence * 100)
        
        report = f"""# AURA Fact-Check Report

**Verification ID:** {verification_id or "N/A"}
**Date:** {datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")}

---

## Claim Under Review

> {claim}

---

## Verdict

| Rating | Confidence |
|--------|------------|
| **{verdict}** | {confidence_pct}% |

---

## Executive Summary

{reasoning}

---

## Methodology

This fact-check was conducted using AURA's multi-stage verification process:

1. **Initial Classification**: AI-powered quick assessment using XLM-RoBERTa model
2. **Evidence Retrieval**: Automated search across trusted sources (WHO, CDC, Reuters, etc.)
3. **Multi-Agent Debate**: Three AI agents (Advocate, Skeptic, Analyst) debated the claim
4. **Judicial Review**: Judge agent evaluated arguments and evidence
5. **Final Determination**: Verdict rendered based on preponderance of evidence

"""
        
        # Add quick classification if available
        if quick_classification:
            qv = quick_classification.get("verdict", "N/A")
            qc = quick_classification.get("confidence", 0)
            report += f"""### Initial Classification

The claim was initially classified as **{qv}** with {int(qc*100)}% confidence by the XLM-RoBERTa model.

"""
        
        # Add debate summary if available
        if debate_summary:
            rounds = debate_summary.get("total_rounds", 4)
            exchanges = debate_summary.get("total_exchanges", 0)
            duration = debate_summary.get("debate_duration_seconds", 0)
            
            report += f"""### Debate Summary

- **Rounds Conducted:** {rounds}
- **Total Exchanges:** {exchanges}
- **Processing Time:** {duration:.1f} seconds

"""
        
        # Add evidence section
        if evidence:
            report += """---

## Evidence Analyzed

| # | Source | Type | Relevance |
|---|--------|------|-----------|
"""
            for i, ev in enumerate(evidence[:10], 1):
                source = ev.get("source", ev.get("domain", "Unknown"))
                ev_type = ev.get("source_type", "web")
                relevance = ev.get("relevance_score", ev.get("combined_score", 0.5))
                report += f"| {i} | {source[:30]} | {ev_type} | {relevance:.0%} |\n"
            
            report += "\n"
        
        # Add disclaimer
        report += """---

## Disclaimer

This fact-check was conducted using automated AI systems. While we strive for accuracy, 
journalists should verify critical information through additional sources before publication.

---

*Generated by AURA Fact-Checker • [aura.in](https://aura.in)*
"""
        
        return report
    
    def _get_sections(self, report: str) -> List[str]:
        """Extract section headers from report."""
        sections = []
        for line in report.split("\n"):
            if line.startswith("## "):
                sections.append(line.replace("## ", "").strip())
        return sections


# Global instance
journalist_response = JournalistResponse()
